### PR TITLE
Leak fix

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
Fixed: 
- Ensure `fclose(f)` is called at the end of the function to properly close the file before returning. This resolves the resource leak issues highlighted in the errors.
```
Checking projet.c ...
projet.c:20:3: error: Resource leak: f [resourceLeak]
  return 0;
  ^
projet.c:43:3: error: Resource leak: f [resourceLeak]
  return 0;
  ^
projet.c:66:3: error: Resource leak: f [resourceLeak]
  return 0;
  ^
```

### CODE REVIEW

**Comment by BernardKD** [comment]
Thanks mglannopoulos24 for your help

**Comment by BernardKD** [comment]
I invite you to inspect all my repository thank you for your help.

**Comment by mgiannopoulos24** [comment]
No problem.

Alright. I'll see what I can do.

**Comment by mgiannopoulos24** [comment]
I checked your other repositories. I havent found any bugs.

**Comment by BernardKD** [comment]
Okay cool. We can work together for new projects in any languages, I want
to perfect 👍

Le jeu. 4 juil. 2024 à 22:31, mgiannopoulos24 ***@***.***> a
écrit :

**Pull request closed without merging**
